# Generated by Django 2.1.13 on 2019-10-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
